#!/usr/bin/env bash

setup_activity_monitor() {
	# Show the main window when launching
	defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

	# Visualize CPU usage in the Dock icon
	defaults write com.apple.ActivityMonitor IconType -int 5

	# Show all processes in
	defaults write com.apple.ActivityMonitor ShowCategory -int 0

	# Sort results by CPU usage
	defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
	defaults write com.apple.ActivityMonitor SortDirection -int 0
}

setup_activity_monitor
