#!/usr/bin/env bash

setup_dashboard() {
	# Dashboard: enable 
	defaults write com.apple.dashboard mcx-disabled -bool true

	# Dashboard: don’t show as a Space
	defaults write com.apple.dock dashboard-in-overlay -bool true

	# Dashboard: enable dev mode (allows keeping widgets on the desktop)
	defaults write com.apple.dashboard devmode -bool true
}

setup_dashboard
