#!/usr/bin/env bash

setup_mail() {
	# Enable send and reply animations in Mail.app
	defaults write com.apple.mail DisableReplyAnimations -bool false
	defaults write com.apple.mail DisableSendAnimations -bool false

	# Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
	defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

	# Display emails in threaded mode, sorted by date (oldest at the top)
	defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
	defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
	defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"

	# Disable inline attachments (show the icons)
	defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

	# Disable automatic spell checking
	# defaults write com.apple.mail SpellCheckingBehavior -string "NoSpellCheckingEnabled"
}

setup_mail
