#!/usr/bin/env bash

setup_photos() {
	# Prevent Photos from opening automatically when devices are plugged in
	defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
}

setup_photos
