#!/usr/bin/env bash

setup_terminal() {
	# Terminal: only use UTF-8
	defaults write com.apple.terminal StringEncodings -array 4

	# Terminal: enable “focus follows mouse” for Terminal.app and all X11 apps
	# i.e. hover over a window and start typing in it without clicking first
	#defaults write com.apple.terminal FocusFollowsMouse -bool true
	#defaults write org.x.X11 wm_ffm -bool true
}

setup_terminal
