#!/usr/bin/env bash

setup_time_machine() {
	# Prevent from prompting to use new hard drives as backup volume
	defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

	# Disable local backups
	hash tmutil &> /dev/null && sudo tmutil disable
}

setup_time_machine
